//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR_Petrov_Fedyaev.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SupplierDetials
    {
        public string Suppliers { get; set; }
        public string NameMaterial { get; set; }
        public string Image { get; set; }
        public decimal Cost { get; set; }
        public int Qty { get; set; }
        public int MinQty { get; set; }
        public int QtyInPackage { get; set; }
        public int IDUnit { get; set; }
        public int ID { get; set; }
        public string Description { get; set; }
        public string NameTypeMaterial { get; set; }
        public int IDTypeMaterial { get; set; }
    }
}
